In [132]:
from pymatgen.ext.matproj import MPRester #Cette cellule permet de télécharger les modules utilsier pour télécharger le fichier
from pymatgen.io.cif import CifWriter     #CIF, avec MPRester qui permet d'accéder à la base de donnée de Material Project (MP)
from pymatgen import Structure            # et CifWriter qui contient les fonctions pour créer un fichier CIF
from jupyter_jsmol.pymatgen import quick_view
from pymatgen.core.operations import SymmOp
from numpy import *

In [133]:
with MPRester("GZeryMtA91usB78Q") as m:                     #Cette cellule utilise ma clé personnelle pour accéder à la base de 
    structure = m.get_structure_by_material_id("mp-675349") #données , la fonction get_ ... permet d'obtenir la structure donnée
                                                            #sur MP

In [134]:
writer = CifWriter(structure,symprec=0.01) #N'ayant pas trouvé de fonction téléchargeant directement le fichier CIF depuis MP je
writer.write_file("mp-675349_download.cif")    # prends la structure et je crée un fichier CIF avec CifWriter à partir de celle-ci
                                           # le paramètre symprec permet de calculer les opérations de symétrie

In [137]:
structure1 =structure
structure2 =structure
structure3 =structure
structure.coords_are_cartesian =True
structure #Affiche la structure pour obtenir les coordonnées des atomes en coordonnées cartésiennes (entre parenthèses)

Structure Summary
Lattice
    abc : 4.098422874617503 4.098422874617503 6.414456
 angles : 90.0 90.0 119.99998183332657
 volume : 93.30911605737492
      A : 2.049212 -3.549338 0.0
      B : 2.049212 3.549338 0.0
      C : 0.0 0.0 6.414456
PeriodicSite: Dy (0.0000, 0.0000, 3.2751) [0.0000, 0.0000, 0.5106]
PeriodicSite: Cu (2.0492, -1.1831, 0.8507) [0.6667, 0.3333, 0.1326]
PeriodicSite: Se (2.0492, 1.1831, 1.5062) [0.3333, 0.6667, 0.2348]
PeriodicSite: Se (2.0492, -1.1831, 4.7985) [0.6667, 0.3333, 0.7481]

## Les opérations de symmétries

Les opérations de symétrie peuvent être calculées grâce aux matrices d'opérations, les calculs présentés dans les cellules suivantes sont fait en coordonnées cartésiennes. Ces données ont été obtenues grâce à l'objet Structure. Afin d'obtenir l'image de la symétrie on applique la matrice S (3x3) au vecteur de l'atome auquel on applique l'opération de symmétrie, x (3x1) afin d'obtenir le vecteur x° donnant la position de l'atome obtenu par symmétrie selon l'équation : \$ x° = S*x \$. Dans les celules suivantes la matrice 3x3 affiché est cette matrice S. Lorsque une opération donne un atome qui n'est pas dans la maille primitive, grâce à la périodicité du réseau, l'atome donnée peut être transposé dans la maille primitive. Cependant les coordonnées données par l'opération de Pymatgen donne la position dans le réseau et non dans la maille une correction manuelle est donc appliquée lorsqu'elle est nécessaire.

In [138]:
Dy = array([0.0000, 0.0000, 3.2751]) #position de l'atome en coordonnée cartésiennes
op1 = SymmOp.from_xyz_string('-y, x-y, z') # définition de l'opération de symétrie ici une rotation selon c
dp1 = op1.operate(Dy) #application de l'opération à l'atome
print(" L'atome de Dysprosium est situé en",Dy,"en coordonnées cartésiennes \n","Il subit une opération de rotation d'un angle de 120° autour du paramètre de maille c donnée par la matrice S: \n",op1.rotation_matrix,"\n Elle se retrouve alors en",dp1,)
print(" Cette opération peut être représentée en 3D grâce à JSmol, cette représentation est montére ci-dessous :","\n (Relancer en cas de non affichage jusqu'à fonctionnment)")
view1 = quick_view(structure1) #les lignes suivantes permettent la visualisation sur jsmol
display(view1)
view1.script('draw symop 2 {atomno=1}') #Relancer en cas de non affichage jusqu'à fonctionnment

 L'atome de Dysprosium est situé en [0.     0.     3.2751] en coordonnées cartésiennes 
 Il subit une opération de rotation d'un angle de 120° autour du paramètre de maille c donnée par la matrice : 
 [[ 0. -1.  0.]
 [ 1. -1.  0.]
 [ 0.  0.  1.]] 
 Elle se retrouve alors en [0.     0.     3.2751]
 Cette opération peut être représentée en 3D grâce à JSmol, cette représentation est montére ci-dessous : 
 (Relancer en cas de non affichage jusqu'à fonctionnment)


JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [145]:
Se =array([2.0492, -1.1831, 4.7985]) #position de l'atome en coordonnée cartésiennes
op2 = SymmOp.from_xyz_string('-y, -x, z') # définition de l'opération de symétrie ici un plan miroir donné par le plan (1 1 0)
dp2 = op2.operate(Se) #application de l'opération à l'atome
print(" L'atome de Sélénium es situé en",Se,"en coordonnées cartésiennes \n","Il subit une opération de plan miroir par le plan (1 1 0) donnée par la matrice S: \n",op2.rotation_matrix,"\n Elle se retrouve alors en",dp2,"dans la maille primitive l'atome équivalent est lui même et donc ")
print(" ses coordonnées sont [ 2.0492 -1.1831  4.7985] ")
print(" Cette opération peut être représentée en 3D grâce à JSmol, cette représentation est montére ci-dessous :","\n (Relancer en cas de non affichage jusqu'à fonctionnment)")
view2 = quick_view(structure2) #les lignes suivantes permettent la visualisation sur jsmol
display(view2)
view2.script('draw symop 4 {atomno=4}') #Relancer en cas de non affichage jusqu'à fonctionnment

 L'atome de Sélénium es situé en [ 2.0492 -1.1831  4.7985] en coordonnées cartésiennes 
 Il subit une opération de plan miroir par le plan (1 1 0) donnée par la matrice S: 
 [[ 0. -1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]] 
 Elle se retrouve alors en [ 1.1831 -2.0492  4.7985] dans la maille primitive l'atome équivalent est lui même et donc 
 ses coordonnées sont [ 2.0492 -1.1831  4.7985] 
 Cette opération peut être représentée en 3D grâce à JSmol, cette représentation est montére ci-dessous : 
 (Relancer en cas de non affichage jusqu'à fonctionnment)


JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [146]:
Cu = array([2.0492, -1.1831, 0.8507]) #position de l'atome en coordonnée cartésiennes
op3 = SymmOp.from_xyz_string('x, x-y, z') # définition de l'opération de symétrie ici un plan miroir donné par le plan (2 -1 0) )
dp3 = op3.operate(Cu) #application de l'opération à l'atome
print(" L'atome de Cuivre situé en",Cu,"en coordonnées cartésiennes \n","Subit une opération de plan miroir à travers le plan (2 1 0) donnée par la matrice : \n",op3.rotation_matrix,"\n Elle se retrouve alors en",dp3,"dans la maille primitive l'atome équivalent est lui même et donc ")
print(" ses coordonnées sont [ 2.0492 -1.1831  0.8507] ")
print(" Cette opération peut être représentée en 3D grâce à JSmol, cette représentation est montére ci-dessous S:","\n (Relancer en cas de non affichage jusqu'à fonctionnment)")
view3 = quick_view(structure3) #les lignes suivantes permettent la visualisation sur jsmol
display(view3)
view3.script('draw symop 5 {atomno=2}') #Relancer en cas de non affichage jusqu'à fonctionnment

 L'atome de Cuivre situé en [ 2.0492 -1.1831  0.8507] en coordonnées cartésiennes 
 Subit une opération de plan miroir à travers le plan (2 1 0) donnée par la matrice : 
 [[ 1.  0.  0.]
 [ 1. -1.  0.]
 [ 0.  0.  1.]] 
 Elle se retrouve alors en [2.0492 3.2323 0.8507] dans la maille primitive l'atome équivalent est lui même et donc 
 ses coordonnées sont [ 2.0492 -1.1831  0.8507] 
 Cette opération peut être représentée en 3D grâce à JSmol, cette représentation est montére ci-dessous S: 
 (Relancer en cas de non affichage jusqu'à fonctionnment)


JsmolView(layout=Layout(align_self='stretch', height='400px'))